server:
  port: 8888

spring:
  application:
    name: sherly-后台管理系统
    dev-flag: true

  # redis配置
  redis:
    host: 101.34.169.185
    port: 6379
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.169.185:3306/sherly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==

  # 适配knife4j高版本
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis-plus配置
mybatis-plus:
  global-config:
    # 逻辑删除
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    # mysql日志
    -com.guzi.upr.mapper: debug
    # knife4j日志
    -springfox: warn

qiniu:
  accessKey: mpw:C1w2szpDQqf4uijVVSKHqkILIG+t7CtJv2/E7yUrKhwu/uoNzzqzaOXTdmj3pjDa
  secretKey: mpw:ox+Km4pN7PXUp6lVylVuPGwvWXde7woVaYLflKRmnAw9SIYS5XrPxWt53dbd82eC
  preUrl: mpw:cqbqoDKQbzM4/uqAyPfXMCJsSiAtI0uH6vVcOS3j5/DoMlfRElR4hMcHVCRxrRET
  bucket: mpw:/21cfcf0uqi4Nkp7ZFaDw+iu9c2QFx6ic6ouXX65qbs=
