sherly:
  dev-flag: false
  default-db: sherly
  default-password: 123456
  default-avatar: https://portrait.gitee.com/uploads/avatars/user/2730/8190589_guzi499_1602830711.png!avatar200
  demo-env: true

server:
  port: 8888

spring:

  # redis配置
  redis:
    host: 101.34.169.185
    port: 6379
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    database: 0
    timeout: 1000

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.169.185:3306/sherly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false

logging:
  file:
    name: .sherly-log/sherly.log
  level:
    # mysql日志
    -com.guzi.upr.mapper: debug
    # knife4j日志
    -springfox: warn

knife4j:
  production: true
