server:
  port: 8888

spring:
  application:
    name: sherly-后台管理系统
    dev-flag: true

  # redis配置
  redis:
    host: 101.34.169.185
    port: 6379

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:2/v3aZvMNujUAwYq09lmjpY/kCU9UjM+bGWUgAg9IxbCAlSBryxryapeNxN3epjg8T57tHS0t4hstpxevRQs+sT2WxThPGiMaTFr1Ri5+0RbxRowXWtWK4oEJLnUfDyiYAkT588s6b47WW//uCVcyNc+VenJKCMq6sC2uycqUeVnC3dWPOEP2lnJsSAGpkEJBFRWFhfmRsORI6bNg30fHxMpJBArEu54gk+Ty1iazcU=
    username: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==

  # 适配knife4j高版本
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis-plus配置
mybatis-plus:
  global-config:
    # 逻辑删除
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    # mysql日志
    -com.guzi.upr.mapper: debug
    # knife4j日志
    -springfox: warn
