
spring:
  profiles:
    active: develop
    default: develop

  application:
    name: sherly-后台管理系统

  # 适配knife4j高版本
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# mybatis-plus配置
mybatis-plus:
  global-config:
    # 逻辑删除
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  documents:
    - locations: classpath:markdown/*
      name: 前后端联调文档
      group: default

