sherly:
  dev-flag: true
  default-password: 123456

server:
  port: 8888

spring:

  # redis配置
  redis:
    host: 101.34.169.185
    port: 6379
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.169.185:3306/sherly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: mpw:tNvIJM/7zuhDi3RoOr2KAA==
    password: mpw:tNvIJM/7zuhDi3RoOr2KAA==

logging:
  file:
    name: .sherly-log/sherly.log
  level:
    # mysql日志
    -com.guzi.upr.mapper: debug
    # knife4j日志
    -springfox: warn
